# Generated by Django 5.0.7 on 2024-08-06 12:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='current_owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_owner', to='cards.user'),
        ),
        migrations.AlterField(
            model_name='card',
            name='previous_owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='previous_owner', to='cards.user'),
        ),
        migrations.AlterField(
            model_name='card',
            name='price',
            field=models.IntegerField(verbose_name=1784),
        ),
        migrations.AlterField(
            model_name='card',
            name='xp_points',
            field=models.IntegerField(verbose_name=2),
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_character', models.CharField(max_length=100)),
                ('price', models.IntegerField(verbose_name=1644)),
                ('current_owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_cards', to='cards.user')),
                ('previous_owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='previous_cards', to='cards.user')),
            ],
        ),
    ]
